### ISSUE TITLE
Incorrect assumption on media location directory

### ISSUE THREAD

**Issue by dantebarba** [dantebarba/autoscan-adapter#6]
### Steps to reproduce

The application is assuming radarr/sonarr-like directory structure for imported media files to optimize Plex library scanning. The issue arises when the directory structure is different than the assumed one.

https://github.com/dantebarba/autoscan-adapter/blob/8e143fe8b636467146ecde93aa249055cf7b903c/plexapihandler.py#L30-L32

Assuming the media_name also has the side effect of potentially selecting the incorrect media to update if the subdirectory name corresponds to another media title.

https://github.com/dantebarba/autoscan-adapter/blob/8e143fe8b636467146ecde93aa249055cf7b903c/plexapihandler.py#L55-L57

https://github.com/dantebarba/autoscan-adapter/blob/8e143fe8b636467146ecde93aa249055cf7b903c/plexapihandler.py#L40-L43

### TODO

- [ ] Reproduce the issue by importing a media file with a different directory structure than radarr/sonarr. Add a test to hit the location manually. Review if error is returned as per #5 
- [ ] Proceed to scrape out the media_name from the Plex section crawler. User section.all() for all operations.
- [ ] Run the python test again.
- [ ] Compare runtime on both cases to review the time-penalty of section.all()
